import type { Catalog } from '@/types';

export const catalog: Catalog[] = [
  { title: 'Most Popular', filter: '/most-popular' },
  { title: 'Recently Updated', filter: '/recently-updated' },
  { title: 'Top Airing', filter: '/top-airing' },
  { title: 'Most Favorite', filter: '/most-favorite' },
  { title: 'Top Upcoming', filter: '/top-upcoming' },
  { title: 'Top Rated', filter: '/top-rated' },
  { title: 'Movie', filter: '/movie' },
  { title: 'TV', filter: '/tv' },
  { title: 'OVA', filter: '/ova' },
  { title: 'ONA', filter: '/ona' },
  { title: 'Special', filter: '/special' },
];

export const genres: Catalog[] = [
  { title: 'Action', filter: '/genre/action' },
  { title: 'Adventure', filter: '/genre/adventure' },
  { title: 'Cars', filter: '/genre/cars' },
  { title: 'Comedy', filter: '/genre/comedy' },
  { title: 'Dementia', filter: '/genre/dementia' },
  { title: 'Demons', filter: '/genre/demons' },
  { title: 'Drama', filter: '/genre/drama' },
  { title: 'Ecchi', filter: '/genre/ecchi' },
  { title: 'Fantasy', filter: '/genre/fantasy' },
  { title: 'Game', filter: '/genre/game' },
  { title: 'Harem', filter: '/genre/harem' },
  { title: 'Historical', filter: '/genre/historical' },
  { title: 'Horror', filter: '/genre/horror' },
  { title: 'Isekai', filter: '/genre/isekai' },
  { title: 'Josei', filter: '/genre/josei' },
  { title: 'Kids', filter: '/genre/kids' },
  { title: 'Magic', filter: '/genre/magic' },
  { title: 'Martial Arts', filter: '/genre/martial-arts' },
  { title: 'Mecha', filter: '/genre/mecha' },
  { title: 'Medical', filter: '/genre/medical' },
  { title: 'Military', filter: '/genre/military' },
  { title: 'Music', filter: '/genre/music' },
  { title: 'Mystery', filter: '/genre/mystery' },
  { title: 'Parody', filter: '/genre/parody' },
  { title: 'Police', filter: '/genre/police' },
  { title: 'Psychological', filter: '/genre/psychological' },
  { title: 'Romance', filter: '/genre/romance' },
  { title: 'Samurai', filter: '/genre/samurai' },
  { title: 'School', filter: '/genre/school' },
  { title: 'Sci-Fi', filter: '/genre/sci-fi' },
  { title: 'Seinen', filter: '/genre/seinen' },
  { title: 'Shoujo', filter: '/genre/shoujo' },
  { title: 'Shoujo Ai', filter: '/genre/shoujo-ai' },
  { title: 'Shounen', filter: '/genre/shounen' },
  { title: 'Shounen Ai', filter: '/genre/shounen-ai' },
  { title: 'Slice of Life', filter: '/genre/slice-of-life' },
  { title: 'Space', filter: '/genre/space' },
  { title: 'Sports', filter: '/genre/sports' },
  { title: 'Super Power', filter: '/genre/super-power' },
  { title: 'Supernatural', filter: '/genre/supernatural' },
  { title: 'Thriller', filter: '/genre/thriller' },
  { title: 'Vampire', filter: '/genre/vampire' },
];