import type { VegaProviderDescriptor } from './vegaAdapter';

/**
 * Upstream Vega inventory. These entries are intentionally not auto-enabled:
 * each provider must be ported through adaptVegaProvider and verified against
 * the current normalized contract before it can make network requests.
 */
export const vegaProviderInventory: VegaProviderDescriptor[] = [
  '1cinevood',
  '4khdhub',
  'Joya9tv',
  'a111477',
  'animetsu',
  'autoEmbed',
  'cinefreak',
  'cinemaLuxe',
  'dooflix',
  'drive',
  'eonMovies',
  'filmyfly',
  'flixhq',
  'gokuHD',
  'guardahd',
  'hdhub4u',
  'hiAnime',
  'katmovies',
  'kickAssAnime',
  'kissKh',
  'kmMovies',
  'luxMovies',
  'mkvDrama',
  'movieBox',
  'movies4u',
  'moviesApi',
  'moviezwap',
  'netflixMirror',
  'ogomovies',
  'primeMirror',
  'primewire',
  'protonMovies',
  'ridoMovies',
  'ringz',
  'showbox',
  'skyMovieHD',
  'theintrodb',
  'tokyoInsider',
  'topmovies',
  'torrentio',
  'uhd',
  'uniquestream',
  'vadapav',
  'vega',
  'world4u',
  'zeefliz',
].map((id) => ({
  id,
  name: id,
  status: 'experimental',
  source: 'vega-adapter',
  note: 'Awaiting contract validation and legal/service health review.',
}));
